In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3])

In [3]:
arr

array([1, 2, 3])

In [7]:
type(arr)

numpy.ndarray

In [8]:
type(arr[0])

numpy.float64

In [6]:
arr=np.array([1,2,3],dtype=float)

In [10]:
arr=np.array([[1,2,3],[3,4,5]])

In [11]:
arr

array([[1, 2, 3],
       [3, 4, 5]])

In [18]:
arr=np.zeros(10,dtype=int)

In [19]:
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
arr=np.ones(10)

In [21]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
arr=np.ones((3,5),dtype=int)

In [25]:
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
arr=np.full((3,5),3.12)

In [27]:
arr

array([[3.12, 3.12, 3.12, 3.12, 3.12],
       [3.12, 3.12, 3.12, 3.12, 3.12],
       [3.12, 3.12, 3.12, 3.12, 3.12]])

In [30]:
arr=np.arange(0,20,1.5)

In [31]:
arr

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ,
       16.5, 18. , 19.5])

In [34]:
arr=np.linspace(2,5,10,dtype=int)

In [35]:
arr

array([2, 2, 2, 3, 3, 3, 4, 4, 4, 5])

In [36]:
arr=np.random.random((3,5))

In [37]:
arr

array([[0.27042336, 0.69606942, 0.40634839, 0.93974214, 0.92774192],
       [0.77629461, 0.39340811, 0.57902364, 0.31187341, 0.63279611],
       [0.25207882, 0.27838344, 0.24880375, 0.17904045, 0.38265053]])

In [41]:
arr=np.random.normal(0,1,(3,2))

In [42]:
arr

array([[-0.35892746,  0.24200355],
       [-0.61665331, -0.51899586],
       [ 0.41881514,  0.56891122]])

In [43]:
arr=np.random.randint(0,10,(3,2))

In [49]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
arr=np.eye((3))

In [53]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [92]:
arr=np.random.randint(2,20,(3,3,4,6))

In [94]:
arr[0][1][3][5]

11

In [96]:
arr.ndim

4

In [97]:
arr.shape

(3, 3, 4, 6)

In [98]:
arr.size

216

In [102]:
arr.dtype

dtype('int32')

In [115]:
np.size(arr[0][2][2][2])

1

In [110]:
arr.itemsize

4

In [111]:
arr.nbytes

864

In [128]:
arr=np.arange(1,13,1)

In [129]:
np.reshape(arr,(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [132]:
arr[:,np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [133]:
x1=np.array([1,2,3])

In [135]:
x2=np.array([[2,3,4],[3,4,5]])

In [139]:
# np.concatenate([x1,x2])
np.vstack([x1,x2])

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [148]:
x3=np.array([[2],[5]])

In [149]:
np.hstack([x2,x3])

array([[2, 3, 4, 2],
       [3, 4, 5, 5]])